services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free  # or any other plan you choose
    envVars:
      - key: FLASK_ENV
        value: production
