services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:8000 app:app"
    plan: free  # Adjust the plan as needed
    envVars:
      - key: FLASK_ENV
        value: production

